import { Link, useSearchParams } from 'remix';
import cn from 'classnames';

import type { Filter, Sort } from '~/routes/$cluster';
import FilterIcon from '~/icons/filter';
import SortIcon from '~/icons/sort';

export default function Nav() {
  const [searchParams] = useSearchParams();
  const sort = (searchParams.get('sort') ?? 'attention_score') as Sort;
  const filter = (searchParams.get('filter') ?? 'hide_retweets') as Filter;
  return (
    <nav className='text-xs mt-2'>
      <SortIcon />
      <span className='relative group'>
        <Link
          className={cn({ underline: sort === 'attention_score' })}
          to={`?filter=${filter}&sort=attention_score`}
        >
          attention score
        </Link>
        <div className='absolute transition-all group-hover:delay-300 group-hover:visible group-hover:opacity-100 group-hover:translate-y-0 -translate-y-1 duration-300 opacity-0 delay-75 invisible top-6 dark:bg-slate-900 bg-white rounded border border-slate-900 dark:border-white p-2.5 w-max max-w-xs'>
          <p>
            Show articles with higher{' '}
            <a
              className='underline'
              href='https://borgcollective.notion.site/FAQ-5434e4695d60456cb481acb98bb88b18'
              target='_blank'
              rel='noopener noreferrer'
            >
              attention score
            </a>{' '}
            sums first.
          </p>
          <p className='mt-1'>
            Each articles attention score sum is calculated by adding together
            the attention scores of each of the articles' tweets' authors. Those
            author attention scores are generated by{' '}
            <a
              className='underline'
              href='https://borgcollective.notion.site/About-15b9db2c1f414cf998c5abc58b715176'
              target='_blank'
              rel='noopener noreferrer'
            >
              the Borg Collective
            </a>{' '}
            for{' '}
            <a
              className='underline'
              href='https://hive.one'
              target='_blank'
              rel='noopener noreferrer'
            >
              Hive
            </a>{' '}
            using their{' '}
            <a
              className='underline'
              href='https://hivedotone.substack.com/p/algorithm-v-21-is-now-live'
              target='_blank'
              rel='noopener noreferrer'
            >
              latest proprietary algorithm for trust
            </a>
            .
          </p>
        </div>
      </span>
      {' · '}
      <Link
        className={cn({ underline: sort === 'tweets_count' })}
        to={`?filter=${filter}&sort=tweets_count`}
        title='Show articles with more influencer tweets first.'
      >
        tweets count
      </Link>
      <FilterIcon />
      <Link
        className={cn({ underline: filter === 'hide_retweets' })}
        to={`?filter=hide_retweets&sort=${sort}`}
        title='Exclude retweets from your ranking algorithm.'
      >
        hide retweets
      </Link>
      {' · '}
      <Link
        className={cn({ underline: filter === 'show_retweets' })}
        to={`?filter=show_retweets&sort=${sort}`}
        title='Include retweets in your ranking algorithm.'
      >
        show retweets
      </Link>
    </nav>
  );
}
